import type { Metadata } from "next";
import "./globals.css";
import LenisProvider from "@/wrappers/LensiProvider";
import { fontVariables } from "./fonts/font";

export const metadata: Metadata = {
  title: "Nayan_Devfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={fontVariables}
      >
        <LenisProvider>
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
